### PR TITLE
fix(cli): set specific version of pnpm for monorepos

### LINKED ISSUE #329: Multirepo pnpm install fails after creation
**Describe the bug**
Create fails for pnpm due to missing version constraint for the package manager field in the package.json

Error:
```
✖ Running `pnpm install`..
file:///Users/xxx/.npm/_npx/ca700ea613ccf9d4/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: pnpm install
Usage Error: Invalid package manager specification in ../../package.json; expected a semver version

$ pnpm ...
    at makeError (file:///Users/xxx/.npm/_npx/ca700ea613ccf9d4/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///Users/xxx/.npm/_npx/ca700ea613ccf9d4/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async S (/Users/xxx/.npm/_npx/ca700ea613ccf9d4/node_modules/@storyblok/field-plugin-cli/dist/main.cjs:1:1594)
    at async R (/Users/xxx/.npm/_npx/ca700ea613ccf9d4/node_modules/@storyblok/field-plugin-cli/dist/main.cjs:7:885)
    at async Pe (/Users/xxx/.npm/_npx/ca700ea613ccf9d4/node_modules/@storyblok/field-plugin-cli/dist/main.cjs:15:77)
    at async Te (/Users/xxx/.npm/_npx/ca700ea613ccf9d4/node_modules/@storyblok/field-plugin-cli/dist/main.cjs:17:401)
    at async Command.<anonymous> (/Users/xxx/.npm/_npx/ca700ea613ccf9d4/node_modules/@storyblok/field-plugin-cli/dist/main.cjs:20:3468) {
  shortMessage: 'Command failed with exit code 1: pnpm install',
  command: 'pnpm install',
  escapedCommand: 'pnpm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'Usage Error: Invalid package manager specification in ../../package.json; expected a semver version\n' +
    '\n' +
    '$ pnpm ...',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**To Reproduce**
1. run `npx @storyblok/field-plugin-cli@latest`
2. Select pnpm
3. Select multirepo, vue 3 (looking at the code this problem probably exists for multiple templates)

**Expected behavior**
Pnpm install starts and succeds.

**Desktop (please complete the following information):**
 - OS: macOS (13 and 14)
 - Versions: Node 18.15.0 with pnpm 8.6.5

### PR DESCRIPTION
**Pull request by hoersamu**
## What?
* Set specific version for pnpm in packageManager field in the package.json file when creating monorepos
* Exclude yarn specific files from monorepos that do not use yarn

## Why?
fixes #329 

* pnpm monorepo creation failed when pnpm is installed using Corepack. This issue was caused by the missing version of the packageManager in the package.json file
* Even if the monorepo was created with a package manager other than yarn the yarn specific config files were copied to the target folder.

## How to test? (optional)
I validated the corepack fix on my machine and tested monorepo creation with all package managers.
I expanded the test for monorepo creation to validate the yarn config file changes.

### CODE REVIEW

File: packages/cli/src/commands/create/monorepo.ts [hunk 1]
```diff
@@ -99,6 +100,11 @@ export const createMonorepo: CreateMonorepoFunc = async ({
       return
     }
 
+    // skip yarn files if yarn is not the package manager
+    if (file.includes('.yarn') && packageManager !== 'yarn') {
+      return
+    }
```
Comment (eunjae-lee) [inline packages/cli/src/commands/create/monorepo.ts:106]:
```suggestion
    if ((file === '.yarn' || file === '.yarnrc') && packageManager !== 'yarn') {
      return
    }
```

what if we go more specific? :)

**Review by eunjae-lee — APPROVED** [review]
Thanks for your contribution! And also thanks for adding the test cases :D 

I've left a feedback, but it's not a blocker.

**Comment by eunjae-lee** [comment]
@all-contributors please add @hoersamu for bug and code.

**Review by eunjae-lee — APPROVED** [review]
Thanks. This looks great ! :)
